ceph_origin: repository
ceph_repository: community
ceph_stable_release: octopus

public_network: "172.16.154.0/24"
cluster_network: "172.16.154.0/24"

ntp_service_enabled: true
ntp_daemon_type: ntpd

dashboard_enabled: False

osd_objectstore: bluestore
osd_scenario: collocated
devices:
  - /dev/sdb

ceph_conf_overrides:
  global:
    osd_pool_default_pg_num: 32
    osd_pool_default_pgp_num: 32
    osd_journal_size: 1024
    osd_pool_default_size: 3
    osd_pool_default_min_size:  2